package com.starhub.model;
// Generated Feb 23, 2017 11:20:31 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HeaderSection generated by hbm2java
 */
@Entity
@Table(name = "header_section", catalog = "starhub")
public class HeaderSection implements java.io.Serializable {

    private Integer id;
    private String mobileLink;
    private String broadbandLink;
    private String tvLink;
    private String homehubLink;

    public HeaderSection() {
    }

    public HeaderSection(String mobileLink, String broadbandLink, String tvLink, String homehubLink) {
        this.mobileLink = mobileLink;
        this.broadbandLink = broadbandLink;
        this.tvLink = tvLink;
        this.homehubLink = homehubLink;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "mobile_link", length = 200)
    public String getMobileLink() {
        return this.mobileLink;
    }

    public void setMobileLink(String mobileLink) {
        this.mobileLink = mobileLink;
    }

    @Column(name = "broadband_link", length = 200)
    public String getBroadbandLink() {
        return this.broadbandLink;
    }

    public void setBroadbandLink(String broadbandLink) {
        this.broadbandLink = broadbandLink;
    }

    @Column(name = "tv_link", length = 200)
    public String getTvLink() {
        return this.tvLink;
    }

    public void setTvLink(String tvLink) {
        this.tvLink = tvLink;
    }

    @Column(name = "homehub_link", length = 200)
    public String getHomehubLink() {
        return this.homehubLink;
    }

    public void setHomehubLink(String homehubLink) {
        this.homehubLink = homehubLink;
    }

}
